### ISSUE TITLE
Video stops playing randomly or does start at all

### ISSUE THREAD

**Issue by fluxxion82** [Chaintech-Network/ComposeMultiplatformMediaPlayer#39]
I've been seeing the video not play or stop playing in the middle of the video randomly, on Android specifically. It looks like there's are some exo player exceptions happening:

<details>
    <summary>Exo player exception</summary>

```
Unexpected exception loading stream
    java.lang.IllegalStateException
      at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
      at androidx.media3.datasource.cache.SimpleCache.startReadWriteNonBlocking(SimpleCache.java:350)
      at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:723)
      at androidx.media3.datasource.cache.CacheDataSource.read(CacheDataSource.java:657)
      at androidx.media3.datasource.StatsDataSource.read(StatsDataSource.java:94)
      at androidx.media3.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:293)
      at androidx.media3.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:70)
      at androidx.media3.exoplayer.source.SampleDataQueue.sampleData(SampleDataQueue.java:178)
      at androidx.media3.exoplayer.source.SampleQueue.sampleData(SampleQueue.java:602)
      at androidx.media3.extractor.TrackOutput.sampleData(TrackOutput.java:161)
      at androidx.media3.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:736)
      at androidx.media3.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:332)
      at androidx.media3.exoplayer.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:147)
      at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1082)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
      at java.lang.Thread.run(Thread.java:1012)
Playback error
  androidx.media3.exoplayer.ExoPlaybackException: Source error
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
      at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:712)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loopOnce(Looper.java:201)
      at android.os.Looper.loop(Looper.java:288)
      at android.os.HandlerThread.run(HandlerThread.java:67)
  Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:442)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
      at java.lang.Thread.run(Thread.java:1012)
  Caused by: java.lang.IllegalStateException
      at androidx.media3.common.util.Assertions.checkState(Assertions.java:85)
      at androidx.media3.datasource.cache.SimpleCache.startReadWriteNonBlocking(SimpleCache.java:350)
      at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:723)
      at androidx.media3.datasource.cache.CacheDataSource.read(CacheDataSource.java:657)
      at androidx.media3.datasource.StatsDataSource.read(StatsDataSource.java:94)
      at androidx.media3.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:293)
      at androidx.media3.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:70)
      at androidx.media3.exoplayer.source.SampleDataQueue.sampleData(SampleDataQueue.java:178)
      at androidx.media3.exoplayer.source.SampleQueue.sampleData(SampleQueue.java:602)
      at androidx.media3.extractor.TrackOutput.sampleData(TrackOutput.java:161)
      at androidx.media3.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:736)
      at androidx.media3.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:332)
      at androidx.media3.exoplayer.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:147)
      at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1082)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
      at java.lang.Thread.run(Thread.java:1012) 
```
</details>

not sure what you can do but maybe you could catch this error and try to restart the playback? the video plays fine a lot of the time so I'm not sure why exoplayer is barfing.

**Comment by ctn-mobile-innovation** [comment]
@fluxxion82 Please check latest version, we had improved for this scenario, Let us know if you face issue again.

**Comment by 0sten** [comment]
I face the same issue. Basically exception is thrown in the scrollable feed where video that is closest to the center is played. Exception is thrown on the 2nd video.

<img width="1031" alt="Image" src="https://github.com/user-attachments/assets/3407104a-9a91-46ca-98f4-dd8376c4fcf9" />

**Comment by ctn-mobile-innovation** [comment]
Please check out the latest version. @fluxxion82 @0sten
